### ISSUE TITLE
Request response of exotic unicode characters seems broken

### ISSUE THREAD

**Issue by Boerrild** [vlingo/vlingo-http#77]
I have tested my xoom-application using the latest vlingo-http-1.6.1-SNAPSHOT (locally build and after fix of vlingo/vlingo-xoom-starter#54). And now it does accept POST requests containing 'exotic' characters like æ, ø and å. However, when querying the value with a subsequent GET-method, it  is no longer the same character that gets back, for instance 'Å' comes back as 'Ã' (second whitespace-character is presented as 'NEL' in my IDE). The response literally crashed my Sapper server with an ERR_STREAM_WRITE_AFTER_END error. I reckon the same would happen for the example app "vlingo-e2e-sys-airline-ops", but I haven't had time to try that out. 

I tried to inspect the values on the 'inside' of my xoom application, and it appears to have 'arrived' correctly, so I guess this time it has to do with serializing the response. Or maybe the response is lacking some encoding hints to the receiver!?

**Comment by VaughnVernon** [comment]
Yes. After fixing the initial problem I realized that it is also a problem with our `Request` and `Response` builders. You can see this in issue #76, which must still be fixed.

**Comment by VaughnVernon** [comment]
Fixed by https://github.com/vlingo/vlingo-http/commit/626bb0226ad1d24b87dc4e8e8469e5d9dc821e1b.

**Comment by Boerrild** [comment]
Even with the latest changes my client was still receiving 'Ã�' instead of 'Å'. My assumption of this being related to some lacking encoding-hints in the response, lead me to further investigate. It turns out, that none of my applications Resources (pre-built by xoom-starter) was configured with a response-header. However, according to https://www.w3.org/Protocols/rfc2616/rfc2616-sec7.html#sec7.2.1: 

_"Any HTTP/1.1 message containing an entity-body SHOULD include a Content-Type header field defining the media type of that body"_

It further states that if not provided and if the client is unable to infer the type, it should be treated as "application/octet-stream" which matches my observations. Adding `ResponseHeader.contentType("application/json; charset=utf-8")` to my responses solved the problem :D

I'll raise a new issue against vlingo-xoom-starter to add the header to the responses of the pre-build resources.

**Comment by Boerrild** [comment]
Created https://github.com/vlingo/vlingo-xoom-starter/issues/57
